

# %% load packages

import os 

import numpy as np 

import torch 
from torch.utils.data import Dataset, DataLoader 
from torchvision import transforms

# import re
import pandas as pd

import tifffile
# from PIL import Image


# %% define dataset (EP Gabor orientations)

# Images were generated by MATLAB (+ PTB3)
# MATLAB codes were adapted from some previous EP studes using oriented Gabors: 
#   Cha, O., & Chong, S. C. (2018). Perceived average orientation reflects effective gist of the surface. Psychological Science, 29(3), 319-327.
#   Jeong, J., & Chong, S. C. (2020). Adaptation to mean and variance: Interrelationships between mean and variance representations in orientation perception. Vision Research, 167, 46-53.
#   Jeong, J., & Chong, S. C. (2021). Perceived variability reflects the reliability of individual items. Vision Research, 183, 91-105.

class EPGabors(Dataset):
    """ Gabor patches having various ensemble statistics (mean, variance, set size).
        The current implementation returns a dictionary of labels for each image. 
        Depending on your task, this label need be transformed or only some of them need be selected

        Structure of file name: 'GaborArray_m{mOri}_sd{SD}_ss{SS}_{instance}.tiff'
            mOri: -12, -8, -4, 0, 4, 8, 12
            SD: 0, 4, 8, 16
            SS: 1, 4, 8, 16, 32
            instance: 1 - 100

        The total number of images would be 14,000 if none of filters is applied.

        # Attributes:
            img_dir: directory of images 
            include_vertical: whether an array with the vertical mean orientation (mOri=0) is included or not 
            include_single: whether a single item (ss=1) condition is included or not
            include_zerovar: whether a homogeneous array (sd=0) is included or not
            filter_ss: a list of ss values that I need to get 
            filter_var: a list of sd values that I need to get  
    """
    def __init__(self, img_dir, include_vertical=True, include_single=False, include_zerovar=True, filter_ss=None, filter_var=None, transform=None):        


        self.img_dir = img_dir 
        # self.task_type = task_type
        self.include_vertical = include_vertical
        self.include_single = include_single 
        self.filter_ss = filter_ss
        self.filter_var = filter_var

        self.transform = transform 

        self.img_list = os.listdir(self.img_dir) # a list of file names  
        # self.img_list = glob.glob(self.img_dir+'/*.tiff')      

        # parsing image list into parameters
        temp_list = [x.split('_') for x in self.img_list]
        list_m = [x[1] for x in temp_list]
        list_m = np.array([int(x[1:]) for x in list_m])

        list_sd = [x[2] for x in temp_list]
        list_sd = np.array([int(x[2:]) for x in list_sd])

        list_ss = [x[3] for x in temp_list]
        list_ss = np.array([int(x[2:]) for x in list_ss]) 

        # make a data frame
        # columns: file_name, mean, sd, ss
        self.df = pd.DataFrame({
            'file_name': self.img_list, 'mean': list_m,
            'sd': list_sd, 'ss': list_ss  
        })

        # filtering out df depending on arguments 
        if not include_vertical:
            # remove vertical mean 
            self.df = self.df[self.df['mean']!= 0]

        if not include_single:
            # remove single item
            self.df = self.df[self.df['ss']!=1]

        if not include_zerovar:
            self.df = self.df[self.df['sd']==0]

        if filter_ss is not None: 
            self.df = self.df[ self.df['ss'].isin(filter_ss)  ]

        if filter_var is not None: 
            self.df = self.df[ self.df['sd'].isin(filter_var)  ]

    def __len__(self):
        return len(self.df)
    
    def __getitem__(self, idx):

        row = self.df.iloc[idx]
        img_path = os.path.join(self.img_dir, row["file_name"])
        # img_path = os.path.join(self.img_dir, self.df.iloc[idx,0])

        image = tifffile.imread(img_path) # numpy array
        # image = torch.tensor(image, dtype=torch.float32)
            
        # label = torch.tensor((self.df.iloc[idx,1:]).astype('int').to_numpy(),dtype=torch.int) # mean, sd, ss
        labels = {
            'mean': torch.tensor(row["mean"], dtype=torch.long),
            'sd': torch.tensor(row["sd"], dtype=torch.long),
            'ss': torch.tensor(row["ss"], dtype=torch.long),
        }
        
        if self.transform is not None:
            image = self.transform(image)
         
        return image, labels